package Assignment_4.Bouns;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

//  Name                    ID
// Ahmed mohmed Abdou   20195008
// Mahmoud Atef         20195007

public class SHI_1Encrypt {
    public static void main(String args[]) throws NoSuchAlgorithmException {
        System.out.println("HashCode Generated by SHA-1 for: ");
        String s1 = "this is java cryptography subject";
        System.out.println("\n" + s1 + " : " + encryptThisString(s1));
        String s2 = "hello world";
        System.out.println("\n" + s2 + " : " + encryptThisString(s2));
    }

    private static String encryptThisString(String s1) throws NoSuchAlgorithmException {
        MessageDigest mDigest = MessageDigest.getInstance("SHA1");
        byte[] result = mDigest.digest(s1.getBytes());
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < result.length; i++) {
            sb.append(Integer.toString((result[i] & 0xff) + 0x100,
                    16).substring(1));
        }
        return sb.toString();
    }

}
